CC = gcc
CFLAGS = -Wall -Wextra -O2 -std=c11
PROGS = privilege_denied crossing_cost

all: $(PROGS)

privilege_denied: privilege_denied.c
crossing_cost: crossing_cost.c

clean:
	rm -f $(PROGS)

.PHONY: all clean
