import { generatePortfolioHtml } from "@/lib/export-html";
import type { Portfolio } from "@/types/portfolio";

/**
 * Minimal ZIP writer (stored / no compression) — avoids a dependency for
 * a simple, genuinely useful "Export ZIP" feature.
 */

const crcTable = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(bytes: Uint8Array): number {
  let c = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) c = crcTable[(c ^ bytes[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

const enc = new TextEncoder();

export function createZip(files: { name: string; content: string | Uint8Array }[]): Blob {
  const chunks: Uint8Array[] = [];
  const central: Uint8Array[] = [];
  let offset = 0;
  const push = (arr: Uint8Array) => {
    chunks.push(arr);
    offset += arr.length;
  };

  for (const f of files) {
    const nameBytes = enc.encode(f.name);
    const data = typeof f.content === "string" ? enc.encode(f.content) : f.content;
    const crc = crc32(data);
    const local = new DataView(new ArrayBuffer(30));
    local.setUint32(0, 0x04034b50, true);
    local.setUint16(4, 20, true);
    local.setUint16(6, 0x0800, true); // UTF-8 filenames
    local.setUint16(8, 0, true); // stored
    local.setUint32(14, crc, true);
    local.setUint32(18, data.length, true);
    local.setUint32(22, data.length, true);
    local.setUint16(26, nameBytes.length, true);
    const header = new Uint8Array(local.buffer);
    push(header);
    push(nameBytes);
    push(data);

    const cen = new DataView(new ArrayBuffer(46));
    cen.setUint32(0, 0x02014b50, true);
    cen.setUint16(4, 20, true);
    cen.setUint16(6, 20, true);
    cen.setUint16(8, 0x0800, true);
    cen.setUint16(10, 0, true);
    cen.setUint32(16, crc, true);
    cen.setUint32(20, data.length, true);
    cen.setUint32(24, data.length, true);
    cen.setUint16(28, nameBytes.length, true);
    cen.setUint32(42, offset - data.length - nameBytes.length - 30, true);
    const c = new Uint8Array(46 + nameBytes.length);
    c.set(new Uint8Array(cen.buffer), 0);
    c.set(nameBytes, 46);
    central.push(c);
  }

  const centralStart = offset;
  let centralSize = 0;
  for (const c of central) {
    chunks.push(c);
    centralSize += c.length;
  }
  const end = new DataView(new ArrayBuffer(22));
  end.setUint32(0, 0x06054b50, true);
  end.setUint16(8, files.length, true);
  end.setUint16(10, files.length, true);
  end.setUint32(12, centralSize, true);
  end.setUint32(16, centralStart, true);
  chunks.push(new Uint8Array(end.buffer));

  return new Blob(chunks as BlobPart[], { type: "application/zip" });
}

export function buildPortfolioZip(p: Portfolio): Blob {
  const html = generatePortfolioHtml(p);
  // Split into index.html + styles.css + README for a tidy, hostable folder.
  const cssMatch = html.match(/<style>([\s\S]*?)<\/style>/);
  const css = cssMatch ? `/* Portfolio styles — generated by Devfolio Builder */\n${cssMatch[1]}` : "";
  const index = cssMatch
    ? html.replace(cssMatch[0], `<link rel="stylesheet" href="styles/main.css">`)
    : html;
  const name = p.profile.name || "portfolio";
  const readme = `# ${name} — Portfolio\n\nStatic portfolio exported from Devfolio Builder.\n\n## Publish\n\n- Drag this folder onto Netlify Drop, Vercel, GitHub Pages, or Cloudflare Pages.\n- Or serve locally: \`npx serve .\` / \`python3 -m http.server\`.\n\n## Files\n\n- \`index.html\` — your portfolio\n- \`styles/main.css\` — styles\n- \`assets/\` — add images here and reference them relatively\n\nYour data: re-import \`portfolio.json\` (exported separately) into the builder anytime.\n`;
  return createZip([
    { name: "portfolio/index.html", content: index },
    { name: "portfolio/styles/main.css", content: css },
    { name: "portfolio/README.md", content: readme },
    { name: "portfolio/assets/.gitkeep", content: "" },
  ]);
}
